version: "3.9"
services:
  springfield:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure:3
    depends_on:
      - mysqldb
    environment:
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
      - APP_POOL_ID=${APP_POOL_ID}
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_PORT=3306

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@123
      - MYSQL_DATABASE=springdb