version: "3.9"
services:
  springfield:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
      - APP_POOL_ID=${APP_POOL_ID}
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_PORT=3306

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@123
      - MYSQL_DATABASE=springdb

  hub:
    image: selenium/hub:4.5.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.5.0
    shm_size: '3gb'
    depends_on:
      - hub
    links:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VNC_NO_PASSWORD=1